const {test}=require('node:test'),assert=require('node:assert/strict');
const {defaults,validate}=require('./preferences.cjs');
const {createBehavior}=require('./pet-behavior.cjs');
const data=(remaining,at=1000)=>({state:'ok',updatedAt:at,accounts:[{owner:'A',provider:'P',windows:[{label:'hour',remaining}]}],users:[{id:'1',remaining:10,used:2}]});
test('opacity defaults, strict ranges and independent values',()=>{assert.equal(validate(defaults).petOpacity,100);assert.equal(validate({...defaults,sidebarOpacity:20}).appOpacity,100);for(const n of [0,19,101,NaN,'50',50.5])assert.throws(()=>validate({...defaults,petOpacity:n}));assert.throws(()=>validate({...defaults,petAnimation:'yes'}));});
test('all quota exhausted, unknown and stale never become exhausted',()=>{const b=createBehavior();assert.equal(b.update(data(0),1000).state,'exhausted');for(const d of [data(null),{...data(0),state:'error'},{...data(0),state:'partial'}, {...data(0),accounts:[]}, {...data(0),accounts:[{error:'offline',windows:[{remaining:0}]}]}])assert.notEqual(b.update(d,1000).state,'exhausted');assert.equal(b.update(data(0),2000).state,'unknown');});
test('quota recovery produces one orbit; preference sends do not replay',()=>{const b=createBehavior();assert.equal(b.update(data(0),1000).event,null);const d=data(100,1001),e=b.update(d,1001).event;assert.equal(e.type,'orbit');assert.equal(b.update(d,1001).event.id,e.id);});
test('credit grant increases trigger love; spending, new users and counter reset do not',()=>{for(const [remaining,used,expected] of [[9,3,null],[20,2,'love'],[20,0,null]]){const b=createBehavior();b.update(data(50),1000);const d=data(49,1001);d.users[0]={id:'1',remaining,used};assert.equal(b.update(d,1001).event?.type??null,expected);}const b=createBehavior();b.update(data(50),1000);const d=data(50,1001);d.users[0].id='other';d.users[0].remaining=100;assert.equal(b.update(d,1001).event,null);});
test('reauth and failed observations reset transition baseline',()=>{const b=createBehavior();b.update(data(0),1000);b.update({state:'auth'},1001);assert.equal(b.update(data(100,1002),1002).event,null);b.reset();assert.equal(b.update(data(100,1003),1003).event,null);});

test('one exhausted window limits each account and old snapshots cannot undo it',()=>{const b=createBehavior(),d=data(70);d.accounts[0].windows.push({label:'week',remaining:0});assert.equal(b.update(d,1000).state,'exhausted');assert.equal(b.update(data(90,999),1000).state,'exhausted');});
